# Generated by Django 4.1.3 on 2022-11-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('education', models.TextField(blank=True)),
                ('key_skills', models.TextField(blank=True)),
                ('languages', models.TextField(blank=True)),
            ],
        ),
    ]
