# Generated by Django 4.1.3 on 2022-12-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0002_cv_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='your photo'),
        ),
    ]
