# Generated by Django 4.1.3 on 2022-12-03 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0003_cv_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastChangedCV',
            fields=[
                ('cv_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cvapp.cv')),
            ],
            bases=('cvapp.cv',),
        ),
        migrations.AlterField(
            model_name='cv',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='your photo'),
        ),
    ]
